# use ram_watch_util_supplement.py in utilities/data/ to generate the dicts at the bottom
def address_to_ram(address = None, location_type = None):
    try:
        if not address:
            print("Must supply address, returning None")
            return None
        elif not location_type:
            print("Must supply location_type (chest or event), returning None")
            return None
        else:
            if location_type == "chest":
                dict_to_use = chest_flag_dict
            elif location_type == "event":
                dict_to_use = event_flag_dict
            else:
                print("Invalid location_type (chest or event), returning None")
                return None
            return dict_to_use[address]
    except Exception as e:
        print("Error on returning %s, %s" % (address, e))
        return None
            
    
    
def ram_to_address(byte = None, bit = None, location_type = None): 
    try:
        if byte == None or bit == None:
            print("Must supply all args, returning None")
            return None
        elif not location_type:
            print("Must supply location_type (chest or event), returning None")
            return None
        else:
            ret = None
        
            if location_type == "chest":
                dict_to_use = chest_flag_dict
            elif location_type == "event":
                dict_to_use = event_flag_dict
            else:
                print("Invalid location_type (chest or event), returning None")
                return None
            
            
            for k, v in dict_to_use.items():
                if v['byte'] == byte and v['bit'] == bit:
                    ret = v        
            if not ret:
                print("No address found, returning None")
                return None
            else:
                return ret
    except Exception as e:
        print("Error on returning %s %s, %s" % (byte, bit, e))
        return None
        
    
    
    
    
    
    
    
    


        
    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    


event_flag_dict = {'C0FAB2': {'name': 'Wind Crystal (Knight)',
  'byte': '0A16',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FAB2'},
 'C0FAB4': {'name': 'Wind Crystal (BlueMage)',
  'byte': '0A16',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FAB4'},
 'C0FAB6': {'name': 'Wind Crystal (BlackMage)',
  'byte': '0A16',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FAB6'},
 'C0FAB8': {'name': 'Wind Crystal (WhiteMage)',
  'byte': '0A16',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FAB8'},
 'C0FABA': {'name': 'Wind Crystal (Monk)',
  'byte': '0A16',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FABA'},
 'C0FABC': {'name': 'Wind Crystal (Thief)',
  'byte': '0A16',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FABC'},
 'C0FABE': {'name': 'Fire Crystal (Trainer)',
  'byte': '0A4F',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FABE'},
 'C0FAC0': {'name': 'Fire Crystal (Geomancer)',
  'byte': '0A4F',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FAC0'},
 'C0FAC2': {'name': 'Fire Crystal (Ninja)',
  'byte': '0A4F',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FAC2'},
 'C0FAC4': {'name': 'Black Choco Crystals (Bard)',
  'byte': '0A29',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FAC4'},
 'C0FAC6': {'name': 'Black Choco Crystals (Hunter)',
  'byte': '0A29',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FAC6'},
 'C0FAC8': {'name': 'Earth Crystal (Samurai)',
  'byte': '0A4F',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FAC8'},
 'C0FACA': {'name': 'Earth Crystal (Dragoon)',
  'byte': '0A4F',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FACA'},
 'C0FACC': {'name': 'Earth Crystal (Chemist)',
  'byte': '0A4F',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FACC'},
 'C0FACE': {'name': 'Earth Crystal (Dancer)',
  'byte': '0A4F',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FACE'},
 'C0FAD0': {'name': 'Leviathan Esper (Levia)',
  'byte': '0A15',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FAD0'},
 'C0FAD2': {'name': 'Titan (Titan)',
  'byte': '0A1E',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FAD2'},
 'C0FAD4': {'name': 'Carbuncle (Crbnkl)',
  'byte': '0A84',
  'bit': '80',
  'direction': 'OFF',
  'address': 'C0FAD4'},
 'C0FAD6': {'name': 'Syldra (Syldra)',
  'byte': '0A3D',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FAD6'},
 'C0FAD8': {'name': 'Odin (Odin)',
  'byte': '0A59',
  'bit': '80',
  'direction': 'OFF',
  'address': 'C0FAD8'},
 'C0FADA': {'name': 'Phoenix (Phenix)',
  'byte': '0A26',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FADA'},
 'C0FADC': {'name': 'Bahamut (Bahmut)',
  'byte': '0A2E',
  'bit': '10',
  'direction': 'ON',
  'address': 'C0FADC'},
 'C0FADE': {'name': 'Life Song (Vitality)',
  'byte': '0A2E',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FADE'},
 'C0FAE0': {'name': 'Temptation Song at Lix (Charm)',
  'byte': '0A2E',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FAE0'},
 'C0FAE2': {'name': 'Love Song at Istory (Love)',
  'byte': '0A36',
  'bit': '02',
  'direction': 'ON',
  'address': 'C0FAE2'},
 'C0FAE4': {'name': 'Requiem Song at Kelb (Requiem)',
  'byte': '0A2E',
  'bit': '02',
  'direction': 'ON',
  'address': 'C0FAE4'},
 'C0FAE6': {'name': 'Speed Song at Surgate (Speed)',
  'byte': '0A30',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FAE6'},
 'C0FAE8': {'name': 'Magic Song at Ancient Library (Magic)',
  'byte': '0A3E',
  'bit': '02',
  'direction': 'ON',
  'address': 'C0FAE8'},
 'C0FAEA': {'name': 'Power Song from Crescent Town (Power)',
  'byte': '0A2D',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FAEA'},
 'C0FAEC': {'name': 'Hero Song from Crescent Town (Hero)',
  'byte': '0A2D',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FAEC'},
 'C0FAEE': {'name': 'Fork Tower, two Magics (Holy)',
  'byte': '0A52',
  'bit': '04',
  'direction': 'ON',
  'address': 'C0FAEE'},
 'C0FAF0': {'name': 'Fork Tower, two Magics (Flare)',
  'byte': '0A52',
  'bit': '04',
  'direction': 'ON',
  'address': 'C0FAF0'},
 'C0FAF2': {'name': 'Meteo (Meteo)',
  'byte': '0A15',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FAF2'},
 'C0FAF4': {'name': '5 potions (from NPC) (Potion)',
  'byte': '0A38',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FAF4'},
 'C0FAF6': {'name': '8 potions (from NPC) (Potion)',
  'byte': '0A3D',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FAF6'},
 'C0FAF8': {'name': 'Chancellor at Tycoon (Healing Staff)',
  'byte': '0A19',
  'bit': '10',
  'direction': 'ON',
  'address': 'C0FAF8'},
 'C0FAFA': {'name': 'Magisa & Forza (Mythril Helm)',
  'byte': '0A18',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FAFA'},
 'C0FAFC': {'name': 'CornaJar at Kelb (CornaJar)',
  'byte': '0A15',
  'bit': '10',
  'direction': 'ON',
  'address': 'C0FAFC'},
 'C0FAFE': {'name': 'Ribbon from girl in Rugor (Ribbon)',
  'byte': '0A41',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FAFE'},
 'C0FB02': {'name': '12 Kuzar Events (Assassin)',
  'byte': '0A78',
  'bit': '10',
  'direction': 'OFF',
  'address': 'C0FB02'},
 'C0FB04': {'name': "12 Kuzar Events (Apollo's Harp)",
  'byte': '0A78',
  'bit': '20',
  'direction': 'OFF',
  'address': 'C0FB04'},
 'C0FB06': {'name': '12 Kuzar Events (Excalibur)',
  'byte': '0A78',
  'bit': '40',
  'direction': 'OFF',
  'address': 'C0FB06'},
 'C0FB08': {'name': '12 Kuzar Events (Flame Whip)',
  'byte': '0A78',
  'bit': '80',
  'direction': 'OFF',
  'address': 'C0FB08'},
 'C0FB0A': {'name': '12 Kuzar Events (Earth Bell)',
  'byte': '0A79',
  'bit': '01',
  'direction': 'OFF',
  'address': 'C0FB0A'},
 'C0FB0C': {'name': '12 Kuzar Events (Holy Lance)',
  'byte': '0A79',
  'bit': '02',
  'direction': 'OFF',
  'address': 'C0FB0C'},
 'C0FB0E': {'name': '12 Kuzar Events (Masamune)',
  'byte': '0A79',
  'bit': '04',
  'direction': 'OFF',
  'address': 'C0FB0E'},
 'C0FB10': {'name': '12 Kuzar Events (Wizard Rod)',
  'byte': '0A79',
  'bit': '08',
  'direction': 'OFF',
  'address': 'C0FB10'},
 'C0FB12': {'name': '12 Kuzar Events (Rune Axe)',
  'byte': '0A79',
  'bit': '10',
  'direction': 'OFF',
  'address': 'C0FB12'},
 'C0FB14': {'name': "12 Kuzar Events (Sage's Staff)",
  'byte': '0A79',
  'bit': '20',
  'direction': 'OFF',
  'address': 'C0FB14'},
 'C0FB16': {'name': '12 Kuzar Events (Hardened Dagger)',
  'byte': '0A79',
  'bit': '40',
  'direction': 'OFF',
  'address': 'C0FB16'},
 'C0FB18': {'name': '12 Kuzar Events (Yoichi Bow)',
  'byte': '0A79',
  'bit': '80',
  'direction': 'OFF',
  'address': 'C0FB18'},
 'C0FB1A': {'name': 'Shiva (Shiva)',
  'byte': '0A18',
  'bit': '20',
  'direction': 'ON',
  'address': 'C0FB1A'},
 'C0FB1C': {'name': 'Ifrit (Ifrit)',
  'byte': '0A86',
  'bit': '80',
  'direction': 'OFF',
  'address': 'C0FB1C'},
 'C0FB1E': {'name': 'Water Crystal (Samurai)',
  'byte': '0A18',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB1E'},
 'C0FB20': {'name': 'Water Crystal (Berserker)',
  'byte': '0A18',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB20'},
 'C0FB22': {'name': 'Water Crystal (MysticKnight)',
  'byte': '0A18',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB22'},
 'C0FB24': {'name': 'Water Crystal (TimeMage)',
  'byte': '0A18',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB24'},
 'C0FB26': {'name': 'Water Crystal (Summoner)',
  'byte': '0A18',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB26'},
 'C0FB28': {'name': 'Brave Blade (Brave Blade)',
  'byte': '0A14',
  'bit': '02',
  'direction': 'ON',
  'address': 'C0FB28'},
 'C0FB2A': {'name': 'Chicken Knife (Chicken Knife)',
  'byte': '0A14',
  'bit': '02',
  'direction': 'ON',
  'address': 'C0FB2A'},
 'C0FB2C': {'name': 'Tycoon Castle Cabin (Cabin)',
  'byte': '0A14',
  'bit': '04',
  'direction': 'ON',
  'address': 'C0FB2C'},
 'C0FB2E': {'name': 'Tycoon Castle Cabin (Cabin)',
  'byte': '0A14',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FB2E'},
 'C0FB30': {'name': 'Walse Tower Chest (GoGo)',
  'byte': '0A71',
  'bit': '08',
  'direction': 'OFF',
  'address': 'C0FB30'},
 'C0FB32': {'name': 'Pyramid Top (Pyramid Tablet)',
  'byte': '0A23',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FB32'},
 'C0FB34': {'name': 'Toad Event (Toad)',
  'byte': '0A36',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FB34'},
 'C0FB36': {'name': 'Aegis Shield Chest (Aegis Shield)',
  'byte': '0A22',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FB36'},
 'C0FB38': {'name': 'Lone Wolf Barrel (Cabin)',
  'byte': '0A24',
  'bit': '20',
  'direction': 'ON',
  'address': 'C0FB38'},
 'C0FB3A': {'name': 'Lone Wolf Chest (Thunder Whip)',
  'byte': '0A15',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FB3A'},
 'C0FB3C': {'name': 'Moat Item (Epee)',
  'byte': '0A47',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FB3C'},
 'C0FB3E': {'name': 'Shop Backdoor (Lamia Harp)',
  'byte': '0A36',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB3E'},
 'C0FB40': {'name': 'Top of the Falls (Magic Lamp)',
  'byte': '0A46',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FB40'},
 'C0FB70': {'name': 'Byblos (Boss)',
  'byte': '0A39',
  'bit': '04',
  'direction': 'ON',
  'address': 'C0FB70'},
 'C0FB72': {'name': 'WingRaptor (Boss)',
  'byte': '0A38',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FB72'},
 'C0FB74': {'name': 'Karlabos (Boss)',
  'byte': '0A38',
  'bit': '04',
  'direction': 'ON',
  'address': 'C0FB74'},
 'C0FB76': {'name': 'Siren (Boss)',
  'byte': '0A18',
  'bit': '02',
  'direction': 'ON',
  'address': 'C0FB76'},
 'C0FB78': {'name': 'Magisa & Forza (Boss)',
  'byte': '0A18',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FB78'},
 'C0FB7A': {'name': 'Galura (Boss)',
  'byte': '0A18',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB7A'},
 'C0FB7C': {'name': 'LiquiFlame (Boss)',
  'byte': '0A19',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB7C'},
 'C0FB7E': {'name': 'Sergeant & DeathClaw (Boss)',
  'byte': '0A1A',
  'bit': '02',
  'direction': 'ON',
  'address': 'C0FB7E'},
 'C0FB80': {'name': 'Sandworm (Boss)',
  'byte': '0A1B',
  'bit': '10',
  'direction': 'ON',
  'address': 'C0FB80'},
 'C0FB82': {'name': 'AdamanTiMi (Boss)',
  'byte': '0A1D',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FB82'},
 'C0FB84': {'name': 'Sol Cannon (Boss)',
  'byte': '0A1D',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FB84'},
 'C0FB86': {'name': 'ArchaeAvis (Boss)',
  'byte': '0A6D',
  'bit': '20',
  'direction': 'OFF',
  'address': 'C0FB86'},
 'C0FB88': {'name': 'Chim.Brain (Boss)',
  'byte': '0A1E',
  'bit': '10',
  'direction': 'ON',
  'address': 'C0FB88'},
 'C0FB8A': {'name': 'Puroboros (Boss)',
  'byte': '0A1E',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FB8A'},
 'C0FB8C': {'name': 'Titan (Boss)',
  'byte': '0A1E',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FB8C'},
 'C0FBB6': {'name': 'Ifrit (Boss)',
  'byte': '0A86',
  'bit': '80',
  'direction': 'OFF',
  'address': 'C0FBB6'},
 'C0FBB8': {'name': 'Shiva (Boss)',
  'byte': '0A18',
  'bit': '20',
  'direction': 'ON',
  'address': 'C0FBB8'},
 'C0FBBA': {'name': 'Crayclaw (Boss)',
  'byte': '0A1C',
  'bit': '10',
  'direction': 'ON',
  'address': 'C0FBBA'},
 'C0FB8E': {'name': 'Gilgamesh 1 (Boss)',
  'byte': '0A1F',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FB8E'},
 'C0FB90': {'name': 'Gilgamesh 2 (Boss)',
  'byte': '0A1C',
  'bit': '20',
  'direction': 'ON',
  'address': 'C0FB90'},
 'C0FB92': {'name': 'Tyrasaurus (Boss)',
  'byte': '0A3B',
  'bit': '10',
  'direction': 'ON',
  'address': 'C0FB92'},
 'C0FB94': {'name': 'Abductor (Boss)',
  'byte': '0A20',
  'bit': '02',
  'direction': 'ON',
  'address': 'C0FB94'},
 'C0FB96': {'name': 'HiryuuPlant (Boss)',
  'byte': '0A20',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FB96'},
 'C0FB98': {'name': 'Gilgamesh 3 & Enkidou (Boss)',
  'byte': '0A29',
  'bit': '04',
  'direction': 'ON',
  'address': 'C0FB98'},
 'C0FB9A': {'name': 'Atmos (Boss)',
  'byte': '0A22',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FB9A'},
 'C0FB9C': {'name': 'Guardians (Boss)',
  'byte': '0A22',
  'bit': '20',
  'direction': 'ON',
  'address': 'C0FB9C'},
 'C0FB9E': {'name': 'Carbunkle (Boss)',
  'byte': '0A84',
  'bit': '80',
  'direction': 'OFF',
  'address': 'C0FB9E'},
 'C0FBA0': {'name': 'Gilgamesh 4 (Boss)',
  'byte': '0A3D',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FBA0'},
 'C0FBA2': {'name': 'Antlion (Boss)',
  'byte': '0A23',
  'bit': '80',
  'direction': 'ON',
  'address': 'C0FBA2'},
 'C0FBA4': {'name': 'Merugene (Boss)',
  'byte': '0A23',
  'bit': '01',
  'direction': 'ON',
  'address': 'C0FBA4'},
 'C0FBA6': {'name': 'Odin (Boss)',
  'byte': '0A59',
  'bit': '80',
  'direction': 'OFF',
  'address': 'C0FBA6'},
 'C0FBA8': {'name': 'Triton, Neregeid & Phobos (Boss)',
  'byte': '0A15',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FBA8'},
 'C0FBAA': {'name': 'Omniscient (Boss)',
  'byte': '0A52',
  'bit': '04',
  'direction': 'ON',
  'address': 'C0FBAA'},
 'C0FBAC': {'name': 'Minotauros (Boss)',
  'byte': '0A52',
  'bit': '04',
  'direction': 'ON',
  'address': 'C0FBAC'},
 'C0FBAE': {'name': 'Leviathan (Boss)',
  'byte': '0A15',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FBAE'},
 'C0FBB0': {'name': 'Stalker (Boss)',
  'byte': '0A3E',
  'bit': '08',
  'direction': 'ON',
  'address': 'C0FBB0'},
 'C0FBB2': {'name': 'GoGo (Boss)',
  'byte': '0A71',
  'bit': '08',
  'direction': 'OFF',
  'address': 'C0FBB2'},
 'C0FBB4': {'name': 'Bahamut (Boss)',
  'byte': '0A2E',
  'bit': '10',
  'direction': 'ON',
  'address': 'C0FBB4'},
 'C0FFFF': {'name': 'Exdeath (Victory)',
  'byte': '0A53',
  'bit': '40',
  'direction': 'ON',
  'address': 'C0FFFF'}}


chest_flag_dict = {'D13212': {'name': 'Wind Shrine Chest (Broadsword)',
  'byte': '09D4',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13212'},
 'D13216': {'name': "Beginner's House Chest (Ether)",
  'byte': '09D4',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13216'},
 'D1321A': {'name': "Beginner's House Chest (100)",
  'byte': '09D4',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1321A'},
 'D1321E': {'name': "Beginner's House Chest (Potion)",
  'byte': '09D4',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1321E'},
 'D13222': {'name': "Beginner's House Chest (Phoenix Down)",
  'byte': '09D4',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13222'},
 'D13226': {'name': "Beginner's House Chest (Tent)",
  'byte': '09D4',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13226'},
 'D1322A': {'name': "Beginner's House Chest MIB 1 (Leather Shoes)",
  'byte': '09D4',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1322A'},
 'D1322E': {'name': "Pirate's Cave Chest (Leather Cap)",
  'byte': '09D4',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1322E'},
 'D13232': {'name': "Pirate's Cave Chest (Tent)",
  'byte': '09D5',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13232'},
 'D13236': {'name': "Pirate's Cave Chest (Ether)",
  'byte': '09D5',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13236'},
 'D1323A': {'name': "Pirate's Cave Chest (300)",
  'byte': '09D5',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1323A'},
 'D1323E': {'name': 'Wind Shrine Chest (Tent)',
  'byte': '09D5',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1323E'},
 'D13242': {'name': 'Wind Shrine Chest (Leather Cap)',
  'byte': '09D5',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13242'},
 'D13246': {'name': 'Wind Shrine Chest (Staff)',
  'byte': '09D5',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13246'},
 'D1324A': {'name': 'Tule Barrel (150)',
  'byte': '09D5',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1324A'},
 'D1324E': {'name': 'Tule Box (Leather Shoes)',
  'byte': '09D5',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1324E'},
 'D13252': {'name': 'Tule Barrel (Potion)',
  'byte': '09D6',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13252'},
 'D13256': {'name': 'Tule Box (Tent)',
  'byte': '09D6',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13256'},
 'D1325A': {'name': 'Tule Bush (Phoenix Down)',
  'byte': '09D6',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1325A'},
 'D1325E': {'name': 'Ship Graveyard Chest (Flail)',
  'byte': '09D6',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1325E'},
 'D13262': {'name': 'Ship Graveyard Chest (Phoenix Down)',
  'byte': '09D6',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13262'},
 'D13266': {'name': 'Ship Graveyard Chest (Tent)',
  'byte': '09D6',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13266'},
 'D1326A': {'name': 'Ship Graveyard Box (990)',
  'byte': '09D6',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1326A'},
 'D1326E': {'name': 'Ship Graveyard Chest (Potion)',
  'byte': '09D6',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1326E'},
 'D13272': {'name': 'Ship Graveyard Chest (Antidote)',
  'byte': '09D7',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13272'},
 'D13276': {'name': 'Ship Graveyard Chest (Antidote)',
  'byte': '09D7',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13276'},
 'D1327A': {'name': 'Ship Graveyard Chest (Phoenix Down)',
  'byte': '09D7',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1327A'},
 'D1327E': {'name': 'Carwen Barrel (Antidote)',
  'byte': '09D7',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1327E'},
 'D13282': {'name': 'Carwen Box (Ice Rod)',
  'byte': '09D7',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13282'},
 'D13286': {'name': 'Carwen Pot (1000)',
  'byte': '09D7',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13286'},
 'D1328A': {'name': 'North Mountain Chest (Soft)',
  'byte': '09D7',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1328A'},
 'D1328E': {'name': 'North Mountain Chest (Phoenix Down)',
  'byte': '09D7',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1328E'},
 'D13292': {'name': 'Walse Town Pot (Glasses)',
  'byte': '09D8',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13292'},
 'D13296': {'name': 'Tycoon Castle Pot (Hi-Potion)',
  'byte': '09D8',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13296'},
 'D1329A': {'name': 'Tycoon Castle Pot (Ether)',
  'byte': '09D8',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1329A'},
 'D1329E': {'name': 'Tycoon Castle Barrel (Elixir)',
  'byte': '09D8',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1329E'},
 'D132A2': {'name': 'Tycoon Castle Barrel (Phoenix Down)',
  'byte': '09D8',
  'bit': '10',
  'direction': 'ON',
  'address': 'D132A2'},
 'D132A6': {'name': 'Tycoon Castle Barrel (Cabin)',
  'byte': '09D8',
  'bit': '20',
  'direction': 'ON',
  'address': 'D132A6'},
 'D132AA': {'name': 'Tycoon Castle Pot (Ether)',
  'byte': '09D8',
  'bit': '40',
  'direction': 'ON',
  'address': 'D132AA'},
 'D132AE': {'name': 'Tycoon Castle Pot (Elixir)',
  'byte': '09D8',
  'bit': '80',
  'direction': 'ON',
  'address': 'D132AE'},
 'D132B2': {'name': 'Tycoon Castle Pot (Phoenix Down)',
  'byte': '09D9',
  'bit': '01',
  'direction': 'ON',
  'address': 'D132B2'},
 'D132B6': {'name': "Tycoon Castle Pot (Maiden's Kiss)",
  'byte': '09D9',
  'bit': '02',
  'direction': 'ON',
  'address': 'D132B6'},
 'D132BA': {'name': 'Tycoon Castle Chest (Shuriken)',
  'byte': '09D9',
  'bit': '04',
  'direction': 'ON',
  'address': 'D132BA'},
 'D132BE': {'name': 'Tycoon Castle Chest (Giyaman)',
  'byte': '09D9',
  'bit': '08',
  'direction': 'ON',
  'address': 'D132BE'},
 'D132C2': {'name': 'Tycoon Castle Chest (Katana)',
  'byte': '09D9',
  'bit': '10',
  'direction': 'ON',
  'address': 'D132C2'},
 'D132C6': {'name': 'Walse Castle Chest (Elf Cape)',
  'byte': '09D9',
  'bit': '20',
  'direction': 'ON',
  'address': 'D132C6'},
 'D132CA': {'name': 'Walse Castle Pot (1000)',
  'byte': '09D9',
  'bit': '40',
  'direction': 'ON',
  'address': 'D132CA'},
 'D132CE': {'name': 'Walse Castle Pot (Drag)',
  'byte': '09D9',
  'bit': '80',
  'direction': 'ON',
  'address': 'D132CE'},
 'D132D2': {'name': 'Walse Castle Pot (1000)',
  'byte': '09DA',
  'bit': '01',
  'direction': 'ON',
  'address': 'D132D2'},
 'D132D6': {'name': 'Walse Castle Box (490)',
  'byte': '09DA',
  'bit': '02',
  'direction': 'ON',
  'address': 'D132D6'},
 'D132DA': {'name': 'Walse Castle Barrel (Tent)',
  'byte': '09DA',
  'bit': '04',
  'direction': 'ON',
  'address': 'D132DA'},
 'D132DE': {'name': 'Walse Castle Barrel (Phoenix Down)',
  'byte': '09DA',
  'bit': '08',
  'direction': 'ON',
  'address': 'D132DE'},
 'D132E2': {'name': 'Walse Tower Chest (Silk robe)',
  'byte': '09DA',
  'bit': '10',
  'direction': 'ON',
  'address': 'D132E2'},
 'D132E6': {'name': "Walse Tower Chest (Maiden's Kiss)",
  'byte': '09DA',
  'bit': '20',
  'direction': 'ON',
  'address': 'D132E6'},
 'D132EA': {'name': 'Walse Tower Chest (Silver Armlet)',
  'byte': '09DA',
  'bit': '40',
  'direction': 'ON',
  'address': 'D132EA'},
 'D132EE': {'name': 'Walse Tower Chest (Ether)',
  'byte': '09DA',
  'bit': '80',
  'direction': 'ON',
  'address': 'D132EE'},
 'D132F2': {'name': 'Tycoon Meteor Chest (Phoenix Down)',
  'byte': '09DB',
  'bit': '01',
  'direction': 'ON',
  'address': 'D132F2'},
 'D132F6': {'name': 'Karnak Castle Chest MIB 1 (Heavy Spear)',
  'byte': '09DB',
  'bit': '02',
  'direction': 'ON',
  'address': 'D132F6'},
 'D132FA': {'name': 'Karnak Castle Chest MIB 2 (Thunder Scroll)',
  'byte': '09DB',
  'bit': '04',
  'direction': 'ON',
  'address': 'D132FA'},
 'D132FE': {'name': 'Karnak Castle Chest (2000)',
  'byte': '09DB',
  'bit': '08',
  'direction': 'ON',
  'address': 'D132FE'},
 'D13302': {'name': 'Karnak Castle Chest MIB 3 (Elixir)',
  'byte': '09DB',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13302'},
 'D13306': {'name': 'Karnak Castle Chest (Elixir)',
  'byte': '09DB',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13306'},
 'D1330A': {'name': 'Karnak Castle Chest (Elixir)',
  'byte': '09DB',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1330A'},
 'D1330E': {'name': 'Karnak Castle Chest (2000)',
  'byte': '09DB',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1330E'},
 'D13312': {'name': 'Karnak Castle Chest (Elixir)',
  'byte': '09DC',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13312'},
 'D13316': {'name': 'Karnak Castle Chest (Elixir)',
  'byte': '09DC',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13316'},
 'D1331A': {'name': 'Karnak Castle Chest (Ribbon)',
  'byte': '09DC',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1331A'},
 'D1331E': {'name': 'Karnak Castle Chest (Shuriken)',
  'byte': '09DC',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1331E'},
 'D13322': {'name': 'Karnak Castle Chest (2000)',
  'byte': '09DC',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13322'},
 'D13326': {'name': 'Karnak Castle Chest (Elixir)',
  'byte': '09DC',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13326'},
 'D1332A': {'name': 'Karnak Castle Chest (Elf Cape)',
  'byte': '09DC',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1332A'},
 'D1332E': {'name': 'Karnak Castle Chest (Guardian)',
  'byte': '09DC',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1332E'},
 'D13332': {'name': 'Karnak Town Barrel (Fire Rod)',
  'byte': '09DD',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13332'},
 'D13336': {'name': 'Steamship Chest (Cabin)',
  'byte': '09DD',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13336'},
 'D1333A': {'name': 'Steamship Chest (Phoenix Down)',
  'byte': '09DD',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1333A'},
 'D1333E': {'name': 'Steamship Chest (Elixir)',
  'byte': '09DD',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1333E'},
 'D13342': {'name': 'Steamship Chest (GrnBeret)',
  'byte': '09DD',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13342'},
 'D13346': {'name': "Steamship Chest (Thief's Glove)",
  'byte': '09DD',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13346'},
 'D1334A': {'name': 'Steamship Chest (Elixir)',
  'byte': '09DD',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1334A'},
 'D1334E': {'name': 'Ancient Library Chest (Ether)',
  'byte': '09DD',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1334E'},
 'D13352': {'name': 'Ancient Library Chest (Phoenix Down)',
  'byte': '09DE',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13352'},
 'D13356': {'name': 'Ancient Library Chest (Stealth Suit)',
  'byte': '09DE',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13356'},
 'D1335A': {'name': 'Jacole Cave Chest (Shuriken)',
  'byte': '09DE',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1335A'},
 'D1335E': {'name': 'Jacole Cave Chest (Tent)',
  'byte': '09DE',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1335E'},
 'D13362': {'name': 'Ruined City Chest (Shuriken)',
  'byte': '09DE',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13362'},
 'D13366': {'name': 'Ruined City Chest (Shuriken)',
  'byte': '09DE',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13366'},
 'D1336A': {'name': 'Ruined City Chest (Size)',
  'byte': '09DE',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1336A'},
 'D1336E': {'name': 'Flying Lonka Ruins Chest (Golden Armor)',
  'byte': '09DE',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1336E'},
 'D13372': {'name': 'Flying Lonka Ruins Chest (Elixir)',
  'byte': '09DF',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13372'},
 'D13376': {'name': 'Flying Lonka Ruins Chest (Phoenix Down)',
  'byte': '09DF',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13376'},
 'D1337A': {'name': 'Flying Lonka Ruins Chest (Golden Shield)',
  'byte': '09DF',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1337A'},
 'D1337E': {'name': 'Steamship Chest (Mythril Glove)',
  'byte': '09DF',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1337E'},
 'D13382': {'name': 'Steamship Chest (Elixir)',
  'byte': '09DF',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13382'},
 'D13386': {'name': 'Steamship Chest (Full Moon)',
  'byte': '09DF',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13386'},
 'D1338A': {'name': 'Flying Lonka Ruins Chest (Hi-Potion)',
  'byte': '09DF',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1338A'},
 'D1338E': {'name': 'Flying Lonka Ruins Chest (5000)',
  'byte': '09DF',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1338E'},
 'D13392': {'name': 'Flying Lonka Ruins Chest (Shuriken)',
  'byte': '09E0',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13392'},
 'D13396': {'name': 'Flying Lonka Ruins Chest (Ancient Sword)',
  'byte': '09E0',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13396'},
 'D1339A': {'name': 'Flying Lonka Ruins Chest (Full Moon)',
  'byte': '09E0',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1339A'},
 'D1339E': {'name': 'Flying Lonka Ruins Chest (Power Wrist)',
  'byte': '09E0',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1339E'},
 'D133A2': {'name': 'Flying Lonka Ruins Chest (Ether)',
  'byte': '09E0',
  'bit': '10',
  'direction': 'ON',
  'address': 'D133A2'},
 'D133A6': {'name': 'Flying Lonka Ruins Chest (Cabin)',
  'byte': '09E0',
  'bit': '20',
  'direction': 'ON',
  'address': 'D133A6'},
 'D133AA': {'name': "Exdeath's Castle Chest (Ether)",
  'byte': '09E0',
  'bit': '40',
  'direction': 'ON',
  'address': 'D133AA'},
 'D133AE': {'name': "Exdeath's Castle Chest (Diamond Shield)",
  'byte': '09E0',
  'bit': '80',
  'direction': 'ON',
  'address': 'D133AE'},
 'D133B2': {'name': "Exdeath's Castle Chest (Ice Shield)",
  'byte': '09E1',
  'bit': '01',
  'direction': 'ON',
  'address': 'D133B2'},
 'D133B6': {'name': "Exdeath's Castle Chest (Ether)",
  'byte': '09E1',
  'bit': '02',
  'direction': 'ON',
  'address': 'D133B6'},
 'D133BA': {'name': "Exdeath's Castle Chest (Elixir)",
  'byte': '09E1',
  'bit': '04',
  'direction': 'ON',
  'address': 'D133BA'},
 'D133BE': {'name': "Exdeath's Castle Chest (Gale Bow)",
  'byte': '09E1',
  'bit': '08',
  'direction': 'ON',
  'address': 'D133BE'},
 'D133C2': {'name': "Exdeath's Castle Chest (IceBrand)",
  'byte': '09E1',
  'bit': '10',
  'direction': 'ON',
  'address': 'D133C2'},
 'D133C6': {'name': "Exdeath's Castle Chest (Kotetsu)",
  'byte': '09E1',
  'bit': '20',
  'direction': 'ON',
  'address': 'D133C6'},
 'D133CA': {'name': "Exdeath's Castle Chest (9900)",
  'byte': '09E1',
  'bit': '40',
  'direction': 'ON',
  'address': 'D133CA'},
 'D133CE': {'name': "Exdeath's Castle Chest (Elixir)",
  'byte': '09E1',
  'bit': '80',
  'direction': 'ON',
  'address': 'D133CE'},
 'D133D2': {'name': "Exdeath's Castle Chest (8000)",
  'byte': '09E2',
  'bit': '01',
  'direction': 'ON',
  'address': 'D133D2'},
 'D133D6': {'name': "Exdeath's Castle Chest (DblLance)",
  'byte': '09E2',
  'bit': '02',
  'direction': 'ON',
  'address': 'D133D6'},
 'D133DA': {'name': "Exdeath's Castle Chest (Partisan)",
  'byte': '09E2',
  'bit': '04',
  'direction': 'ON',
  'address': 'D133DA'},
 'D133DE': {'name': "Exdeath's Castle Chest (Pinwheel)",
  'byte': '09E2',
  'bit': '08',
  'direction': 'ON',
  'address': 'D133DE'},
 'D133E2': {'name': 'Moogle Cave Chest (4400)',
  'byte': '09E2',
  'bit': '10',
  'direction': 'ON',
  'address': 'D133E2'},
 'D133E6': {'name': 'Moogle Cave Chest (Phoenix Down)',
  'byte': '09E2',
  'bit': '20',
  'direction': 'ON',
  'address': 'D133E6'},
 'D133EA': {'name': 'Moogle Village Chest (Cabin)',
  'byte': '09E2',
  'bit': '40',
  'direction': 'ON',
  'address': 'D133EA'},
 'D133EE': {'name': 'Moogle Village Chest (Dancing Dagger)',
  'byte': '09E2',
  'bit': '80',
  'direction': 'ON',
  'address': 'D133EE'},
 'D133F2': {'name': 'Moogle Village Chest (1)',
  'byte': '09E3',
  'bit': '01',
  'direction': 'ON',
  'address': 'D133F2'},
 'D133F6': {'name': 'Moogle Village Chest (10000)',
  'byte': '09E3',
  'bit': '02',
  'direction': 'ON',
  'address': 'D133F6'},
 'D133FA': {'name': 'Moogle Village Chest (Phoenix Down)',
  'byte': '09E3',
  'bit': '04',
  'direction': 'ON',
  'address': 'D133FA'},
 'D133FE': {'name': 'Moogle Village Chest (Ether)',
  'byte': '09E3',
  'bit': '08',
  'direction': 'ON',
  'address': 'D133FE'},
 'D13402': {'name': 'Moogle Village Chest (Elf Cape)',
  'byte': '09E3',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13402'},
 'D13406': {'name': 'Bal Castle Chest (Angel Gwn)',
  'byte': '09E3',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13406'},
 'D1340A': {'name': 'Bal Castle Chest (Hero Drink)',
  'byte': '09E3',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1340A'},
 'D1340E': {'name': 'Bal Castle Chest (Exit)',
  'byte': '09E3',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1340E'},
 'D13412': {'name': 'Hiryuu Valley Skull (Bone Mail)',
  'byte': '09E4',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13412'},
 'D13416': {'name': 'Hiryuu Valley Chest (5000)',
  'byte': '09E4',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13416'},
 'D1341A': {'name': 'Hiryuu Valley Chest (Cabin)',
  'byte': '09E4',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1341A'},
 'D1341E': {'name': 'Hiryuu Valley Chest (7000)',
  'byte': '09E4',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1341E'},
 'D13422': {'name': 'Hiryuu Valley Chest (Hypno Helm)',
  'byte': '09E4',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13422'},
 'D13426': {'name': 'Hiryuu Valley Chest (Air Blade)',
  'byte': '09E4',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13426'},
 'D1342A': {'name': 'Hiryuu Valley Chest (Phoenix Down)',
  'byte': '09E4',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1342A'},
 'D1342E': {'name': 'Surgate Castle Chest (5000)',
  'byte': '09E4',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1342E'},
 'D13432': {'name': 'Surgate Castle Chest (Float)',
  'byte': '09E5',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13432'},
 'D13436': {'name': 'Barrier Tower Chest MIB 1 (Drain Sword)',
  'byte': '09E5',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13436'},
 'D1343A': {'name': 'Barrier Tower Chest (9000)',
  'byte': '09E5',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1343A'},
 'D1343E': {'name': 'Barrier Tower Chest (18000)',
  'byte': '09E5',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1343E'},
 'D13442': {'name': 'Barrier Tower Chest MIB 2 (Gold Hairpin)',
  'byte': '09E5',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13442'},
 'D13446': {'name': 'Mua Town Barrel (Guardian)',
  'byte': '09E5',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13446'},
 'D1344A': {'name': 'Mua Forest Chest (2500)',
  'byte': '09E5',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1344A'},
 'D1344E': {'name': 'Mua Forest Chest (Ether)',
  'byte': '09E5',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1344E'},
 'D13452': {'name': 'Mua Forest Chest (4900)',
  'byte': '09E6',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13452'},
 'D13456': {'name': 'Mua Forest Chest (Phoenix Down)',
  'byte': '09E6',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13456'},
 'D1345A': {'name': 'Mua Forest Chest (9500)',
  'byte': '09E6',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1345A'},
 'D1345E': {'name': 'Mua Forest Chest (Soot)',
  'byte': '09E6',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1345E'},
 'D13462': {'name': 'Mua Forest Chest (Flametongue)',
  'byte': '09E6',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13462'},
 'D13466': {'name': 'Mua Forest Chest (Cabin)',
  'byte': '09E6',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13466'},
 'D1346A': {'name': 'Mua Forest Chest (Giant Drink)',
  'byte': '09E6',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1346A'},
 'D1346E': {'name': 'Mua Forest Chest (Elixir)',
  'byte': '09E6',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1346E'},
 'D13472': {'name': 'Mua Forest Chest (Morning Star)',
  'byte': '09E7',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13472'},
 'D13476': {'name': 'Solitary Island Chest (Ether)',
  'byte': '09E7',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13476'},
 'D1347A': {'name': 'Solitary Island Chest (DragonFang)',
  'byte': '09E7',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1347A'},
 'D1347E': {'name': 'Pyramid Chest (Elixir)',
  'byte': '09E7',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1347E'},
 'D13482': {'name': 'Pyramid Chest (Elixir)',
  'byte': '09E7',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13482'},
 'D13486': {'name': 'Pyramid Chest MIB 1 (Black Robe)',
  'byte': '09E7',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13486'},
 'D1348A': {'name': 'Pyramid Chest (Thornlet)',
  'byte': '09E7',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1348A'},
 'D1348E': {'name': 'Pyramid Chest MIB 2 (DarkMatter)',
  'byte': '09E7',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1348E'},
 'D13492': {'name': 'Pyramid Chest MIB 3 (Crystal Armor)',
  'byte': '09E8',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13492'},
 'D13496': {'name': 'Pyramid Chest (Cursed Ring)',
  'byte': '09E8',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13496'},
 'D1349A': {'name': 'Pyramid Chest (Ice Shield)',
  'byte': '09E8',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1349A'},
 'D1349E': {'name': 'Pyramid Chest (Flame Shield)',
  'byte': '09E8',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1349E'},
 'D134A2': {'name': 'Pyramid Chest (DarkMatter)',
  'byte': '09E8',
  'bit': '10',
  'direction': 'ON',
  'address': 'D134A2'},
 'D134A6': {'name': 'Pyramid Chest (White Robe)',
  'byte': '09E8',
  'bit': '20',
  'direction': 'ON',
  'address': 'D134A6'},
 'D134AA': {'name': 'Pyramid Chest (DarkSuit)',
  'byte': '09E8',
  'bit': '40',
  'direction': 'ON',
  'address': 'D134AA'},
 'D134AE': {'name': 'Pyramid Chest (DarkMatter)',
  'byte': '09E8',
  'bit': '80',
  'direction': 'ON',
  'address': 'D134AE'},
 'D134B2': {'name': 'Pyramid Chest (DarkMatter)',
  'byte': '09E9',
  'bit': '01',
  'direction': 'ON',
  'address': 'D134B2'},
 'D134B6': {'name': 'Pyramid Chest (DarkMatter)',
  'byte': '09E9',
  'bit': '02',
  'direction': 'ON',
  'address': 'D134B6'},
 'D134BA': {'name': 'Pyramid Chest (9000)',
  'byte': '09E9',
  'bit': '04',
  'direction': 'ON',
  'a09E8ddress': 'D134BA'},
 'D134BE': {'name': 'Pyramid Chest (8000)',
  'byte': '09E9',
  'bit': '08',
  'direction': 'ON',
  'address': 'D134BE'},
 'D134C2': {'name': 'Pyramid Chest (Earth Hammer)',
  'byte': '09E9',
  'bit': '10',
  'direction': 'ON',
  'address': 'D134C2'},
 'D134C6': {'name': 'Pyramid Chest (10000)',
  'byte': '09E9',
  'bit': '20',
  'direction': 'ON',
  'address': 'D134C6'},
 'D134CA': {'name': 'Pyramid Chest (Cabin)',
  'byte': '09E9',
  'bit': '40',
  'direction': 'ON',
  'address': 'D134CA'},
 'D134CE': {'name': 'Pyramid Chest (Elixir)',
  'byte': '09E9',
  'bit': '80',
  'direction': 'ON',
  'address': 'D134CE'},
 'D134D2': {'name': 'Pyramid Chest (12000)',
  'byte': '09EA',
  'bit': '01',
  'direction': 'ON',
  'address': 'D134D2'},
 'D134D6': {'name': 'Pyramid Chest (DarkMatter)',
  'byte': '09EA',
  'bit': '02',
  'direction': 'ON',
  'address': 'D134D6'},
 'D134DA': {'name': 'Pyramid Chest (Elixir)',
  'byte': '09EA',
  'bit': '04',
  'direction': 'ON',
  'address': 'D134DA'},
 'D134DE': {'name': 'Pyramid Chest (DarkMatter)',
  'byte': '09EA',
  'bit': '08',
  'direction': 'ON',
  'address': 'D134DE'},
 'D134E2': {'name': 'Pyramid Chest (Guard Ring)',
  'byte': '09EA',
  'bit': '10',
  'direction': 'ON',
  'address': 'D134E2'},
 'D134E6': {'name': 'Pyramid Chest (Ribbon)',
  'byte': '09EA',
  'bit': '20',
  'direction': 'ON',
  'address': 'D134E6'},
 'D134EA': {'name': 'Pyramid Chest (Gold Hairpin)',
  'byte': '09EA',
  'bit': '40',
  'direction': 'ON',
  'address': 'D134EA'},
 'D134EE': {'name': 'Solitary Island Chest (12000)',
  'byte': '09EA',
  'bit': '80',
  'direction': 'ON',
  'address': 'D134EE'},
 'D134F2': {'name': 'Solitary Island Chest (Hi-Potion)',
  'byte': '09EB',
  'bit': '01',
  'direction': 'ON',
  'address': 'D134F2'},
 'D134F6': {'name': 'Solitary Island Chest (Protect Drink)',
  'byte': '09EB',
  'bit': '02',
  'direction': 'ON',
  'address': 'D134F6'},
 'D134FA': {'name': 'Solitary Island Chest (BeastKiller)',
  'byte': '09EB',
  'bit': '04',
  'direction': 'ON',
  'address': 'D134FA'},
 'D134FE': {'name': 'Solitary Island Chest MIB 1 (RisingSun)',
  'byte': '09EB',
  'bit': '08',
  'direction': 'ON',
  'address': 'D134FE'},
 'D13502': {'name': 'Solitary Island Chest (Ether)',
  'byte': '09EB',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13502'},
 'D13506': {'name': 'Solitary Island Chest MIB 2 (Guard Ring)',
  'byte': '09EB',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13506'},
 'D1350A': {'name': 'Solitary Island Chest (Crystal Helm)',
  'byte': '09EB',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1350A'},
 'D1350E': {'name': 'Solitary Island Chest (9000)',
  'byte': '09EB',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1350E'},
 'D13512': {'name': 'Solitary Island Chest (Elixir)',
  'byte': '09EC',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13512'},
 'D13516': {'name': 'Solitary Island Chest (DarkMatter)',
  'byte': '09EC',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13516'},
 'D1351A': {'name': 'Solitary Island Chest (Circlet)',
  'byte': '09EC',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1351A'},
 'D1351E': {'name': 'Fork Tower L. Chest (Ether)',
  'byte': '09EC',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1351E'},
 'D13522': {'name': 'Fork Tower L. Chest (Wonder Wand)',
  'byte': '09EC',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13522'},
 'D13526': {'name': 'Fork Tower R. Chest (Hi-Potion)',
  'byte': '09EC',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13526'},
 'D1352A': {'name': 'Fork Tower R. Chest (Defender Sword)',
  'byte': '09EC',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1352A'},
 'D1352E': {'name': 'Great Trench Chest (Water Scroll)',
  'byte': '09EC',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1352E'},
 'D13532': {'name': 'Great Trench Chest (Flame Ring)',
  'byte': '09ED',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13532'},
 'D13536': {'name': 'Great Trench Chest (DragonFang)',
  'byte': '09ED',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13536'},
 'D1353A': {'name': 'Great Trench Chest (Ether)',
  'byte': '09ED',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1353A'},
 'D1353E': {'name': 'Great Trench Chest (Phoenix Down)',
  'byte': '09ED',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1353E'},
 'D13542': {'name': 'Great Trench Chest (Kaiser Knuckles)',
  'byte': '09ED',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13542'},
 'D13546': {'name': 'Istory Falls Chest (Ether)',
  'byte': '09ED',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13546'},
 'D1354A': {'name': 'Istory Falls Chest (TurtleShell)',
  'byte': '09ED',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1354A'},
 'D1354E': {'name': 'Istory Falls Chest (Air Knife)',
  'byte': '09ED',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1354E'},
 'D13552': {'name': 'Istory Falls Chest (Giant Drink)',
  'byte': '09EE',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13552'},
 'D13556': {'name': 'Istory Falls Chest (RuneEdge)',
  'byte': '09EE',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13556'},
 'D1355A': {'name': 'Istory Falls Chest (Guard Ring)',
  'byte': '09EE',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1355A'},
 'D1355E': {'name': 'Istory Falls Chest (Wall Ring)',
  'byte': '09EE',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1355E'},
 'D13562': {'name': 'Istory Falls Chest (Phoenix Down)',
  'byte': '09EE',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13562'},
 'D13566': {'name': 'Istory Falls Chest (Enhancer)',
  'byte': '09EE',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13566'},
 'D1356A': {'name': 'Istory Falls Chest (12000)',
  'byte': '09EE',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1356A'},
 'D1356E': {'name': 'Istory Falls Chest (Artemis Bow)',
  'byte': '09EE',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1356E'},
 'D13572': {'name': 'Istory Falls Chest (Pinwheel)',
  'byte': '09EF',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13572'},
 'D13576': {'name': 'Istory Falls Chest (Aegis Shield)',
  'byte': '09EF',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13576'},
 'D1357A': {'name': "Istory Falls Chest (Giant's Axe)",
  'byte': '09EF',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1357A'},
 'D1357E': {'name': 'Phoenix Tower Pot (5000)',
  'byte': '09EF',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1357E'},
 'D13582': {'name': 'Phoenix Tower Pot (Phoenix Down)',
  'byte': '09EF',
  'bit': '10',
  'direction': 'ON',
  'address': 'D13582'},
 'D13586': {'name': 'Phoenix Tower Pot (10000)',
  'byte': '09EF',
  'bit': '20',
  'direction': 'ON',
  'address': 'D13586'},
 'D1358A': {'name': 'Phoenix Tower Pot (Phoenix Down)',
  'byte': '09EF',
  'bit': '40',
  'direction': 'ON',
  'address': 'D1358A'},
 'D1358E': {'name': 'Phoenix Tower Pot (Phoenix Down)',
  'byte': '09EF',
  'bit': '80',
  'direction': 'ON',
  'address': 'D1358E'},
 'D13592': {'name': 'Phoenix Tower Pot (15000)',
  'byte': '09F0',
  'bit': '01',
  'direction': 'ON',
  'address': 'D13592'},
 'D13596': {'name': 'Phoenix Tower Pot (20000)',
  'byte': '09F0',
  'bit': '02',
  'direction': 'ON',
  'address': 'D13596'},
 'D1359A': {'name': 'Phoenix Tower Pot (Phoenix Down)',
  'byte': '09F0',
  'bit': '04',
  'direction': 'ON',
  'address': 'D1359A'},
 'D1359E': {'name': 'Phoenix Tower Pot (Avis Killer)',
  'byte': '09F0',
  'bit': '08',
  'direction': 'ON',
  'address': 'D1359E'},
 'D135A2': {'name': 'Phoenix Tower Pot (25000)',
  'byte': '09F0',
  'bit': '10',
  'direction': 'ON',
  'address': 'D135A2'},
 'D135A6': {'name': 'Mirage Village Barrel (Thief Knife)',
  'byte': '09F0',
  'bit': '20',
  'direction': 'ON',
  'address': 'D135A6'},
 'D135AA': {'name': 'Rift (Ruins) Chest (Ether)',
  'byte': '09F0',
  'bit': '40',
  'direction': 'ON',
  'address': 'D135AA'},
 'D135AE': {'name': 'Rift (Ruins) Chest (Cabin)',
  'byte': '09F0',
  'bit': '80',
  'direction': 'ON',
  'address': 'D135AE'},
 'D135B2': {'name': 'Rift (Ruins) Chest (Elixir)',
  'byte': '09F1',
  'bit': '01',
  'direction': 'ON',
  'address': 'D135B2'},
 'D135B6': {'name': 'Rift (Ruins) Chest (DarkMatter)',
  'byte': '09F1',
  'bit': '02',
  'direction': 'ON',
  'address': 'D135B6'},
 'D135BA': {'name': 'Rift (Ruins) Chest (Elixir)',
  'byte': '09F1',
  'bit': '04',
  'direction': 'ON',
  'address': 'D135BA'},
 'D135BE': {'name': 'Rift (Ruins) Chest (Drain Sword)',
  'byte': '09F1',
  'bit': '08',
  'direction': 'ON',
  'address': 'D135BE'},
 'D135C2': {'name': 'Rift (Forest) Chest (DragonFang)',
  'byte': '09F1',
  'bit': '10',
  'direction': 'ON',
  'address': 'D135C2'},
 'D135C6': {'name': 'Rift (Forest) Chest (Ribbon)',
  'byte': '09F1',
  'bit': '20',
  'direction': 'ON',
  'address': 'D135C6'},
 'D135CA': {'name': 'Rift (Forest) Chest (Enhancer)',
  'byte': '09F1',
  'bit': '40',
  'direction': 'ON',
  'address': 'D135CA'},
 'D135CE': {'name': 'Rift (Forest) Chest (Lillith Rod)',
  'byte': '09F1',
  'bit': '80',
  'direction': 'ON',
  'address': 'D135CE'},
 'D135D2': {'name': 'Rift (Cave) Chest (Angel Ring)',
  'byte': '09F2',
  'bit': '01',
  'direction': 'ON',
  'address': 'D135D2'},
 'D135D6': {'name': 'Rift (Cave) Chest (Coral Ring)',
  'byte': '09F2',
  'bit': '02',
  'direction': 'ON',
  'address': 'D135D6'},
 'D135DA': {'name': 'Rift (Castle) Chest (Thor Hammer)',
  'byte': '09F2',
  'bit': '04',
  'direction': 'ON',
  'address': 'D135DA'},
 'D135DE': {'name': 'Rift (Castle) Chest (Running Shoes)',
  'byte': '09F2',
  'bit': '08',
  'direction': 'ON',
  'address': 'D135DE'},
 'D135E2': {'name': 'Rift (Castle) Chest (Red Shoes)',
  'byte': '09F2',
  'bit': '10',
  'direction': 'ON',
  'address': 'D135E2'},
 'D135E6': {'name': 'Rift (Castle) Chest (Rainbow Dress)',
  'byte': '09F2',
  'bit': '20',
  'direction': 'ON',
  'address': 'D135E6'},
 'D135EA': {'name': 'Rift (Castle) Chest (ManEater)',
  'byte': '09F2',
  'bit': '40',
  'direction': 'ON',
  'address': 'D135EA'},
 'D135EE': {'name': 'The Void Chest (Pinwheel)',
  'byte': '09F2',
  'bit': '80',
  'direction': 'ON',
  'address': 'D135EE'},
 'D135F2': {'name': 'The Void Chest (Pinwheel)',
  'byte': '09F3',
  'bit': '01',
  'direction': 'ON',
  'address': 'D135F2'},
 'D135F6': {'name': 'The Void Chest (Elixir)',
  'byte': '09F3',
  'bit': '02',
  'direction': 'ON',
  'address': 'D135F6'},
 'D135FA': {'name': 'The Void Chest (Ragnarok)',
  'byte': '09F3',
  'bit': '04',
  'direction': 'ON',
  'address': 'D135FA'},
 'D135FE': {'name': 'The Void Chest (Pinwheel)',
  'byte': '09F3',
  'bit': '08',
  'direction': 'ON',
  'address': 'D135FE'}}  

full_flag_dict = {**event_flag_dict, **chest_flag_dict}